services:
    Erichard\GlideBundle\Controller\GlideController:
        public: true
        calls: [['setContainer', ['@Psr\Container\ContainerInterface']]]
        tags: ['container.service_subscriber']
        
    Erichard\GlideBundle\GlideUrlBuilder:
        public: false
        arguments:
            $signkey: "%erichard_glide.sign_key%"

    Erichard\GlideBundle\Twig\GlideExtension:
        public: false
        arguments:
            - "@Erichard\\GlideBundle\\GlideUrlBuilder"
        tags:
            - { name: twig.extension }

    erichard_glide.symfony_response_factory:
        class: Erichard\GlideBundle\SymfonyResponseFactory
        public: false

    erichard_glide.server:
        class: League\Glide\Server
        public: true
        abstract: true
        factory: [ League\Glide\ServerFactory, 'create' ]
        arguments:
            - ~
